hello_the_world:
    path: /hello-world
    defaults: { _controller: BOWPlatformBundle:Advert:index }

byebye_the_world:
    path: /byebye-world
    defaults: { _controller: BOWPlatformBundle:Advert:byebye }
